### PR TITLE
feat: rewrite omreport ssv parsing logic

### PR DESCRIPTION
**Pull request by galexrt**
Still needs to be tested in the real world. If anyone has capacities to build and test out this PR, it would be good to know if the changes work as expected as I can only work of the `omreport` test outputs that are currently in the code.

### CODE REVIEW

**Comment by B0go** [comment]
@galexrt I ran a test in one of our boxes.

To compile the binary, I cloned the repository and build the binary inside /cmd/dellhw_exporter  using `go build -o dellhw_exporter .`. Then I configured my systemd service to use it, with no configuration changes.

From what I could see in your pull request, the new chassis_info collector should be enabled by default, right? It seems it was not enabled in the first run tho:

```
Oct 16 14:02:37 kvm-111 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg="Starting dellhw_exporter (version=, branch=, revision=2d742cdfd2782eccf81f2e1aa92e1b463724c2eb)"
Oct 16 14:02:37 kvm-111 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg="Build context (go=go1.23.2, platform=linux/amd64, user=, date=, tags=unknown)"
Oct 16 14:02:37 kvm-111 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg="Setting command timeout to 15"
Oct 16 14:02:37 kvm-111 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg="Caching enabled. Cache Duration: 15s"
Oct 16 14:02:37 kvm-111 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg="Enabled collectors:"
Oct 16 14:02:37 kvm-111 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - chassis_batteries"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - firmwares"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - storage_battery"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - ps_amps_sysboard_pwr"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - storage_vdisk"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - system"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - chassis"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - fans"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - memory"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - nics"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - ps"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - version"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - volts"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - processors"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - temps"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - storage_controller"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - storage_enclosure"
Oct 16 14:02:37 dellhw_exporter[2726843]: time="2024-10-16T14:02:37Z" level=info msg=" - storage_pdisk"
```
Revision points to your latest commit [2d742cdfd2782eccf81f2e1aa92e1b463724c2eb](https://github.com/galexrt/dellhw_exporter/pull/134/commits/2d742cdfd2782eccf81f2e1aa92e1b463724c2eb) so the output is indeed from the new binary

I also noticed that at least one of the metrics changed from 0 to 1, still need to investigate if the new version fixed an broken metric or caused some sort of bug:
Screenshot 2024-10-16 at 11 35 01

**Comment by B0go** [comment]
The output for the chassis bateries on that box is:
```
omreport chassis batteries -fmt ssv
Batteries

Health;Ok

Individual Battery Elements

Index;Status;Probe Name;Reading
0;Ok;System Board CMOS Battery;Good
```
So the changes either changed the value of "good" from 0 to 1 or introduced a bug that is causing the metric to be reported with an unexpected value

**Comment by galexrt** [comment]
@B0go Thank you very much! Greatly appreciate you taking the time to test and the output of the chassis batteries. I had forgotten that I was missing that output in the tests and couldn't fully write the test/logic for parsing the chassis batteries output.

I have pushed commits to this branch that should fix the chassis batteries metrics reporting the wrong value.

I will probably move ahead and merge this PR by beginning of next week as I think with your test and the existing code test cases it should be reasonable to release a release candidate soon.

**Comment by galexrt** [comment]
@B0go I have updated the docs, the `chassis_info` collector is not enabled by default. To make enabling disabled collectors easier for future additions, I have added the `--collectors-additional` flag with which you can do `--collectors-additional=chassis_info` to keep all the default enabled collectors active and add the `chassis_info` one without having to specify the whole list of collectors to the `--collectors-enabled` flag.

**Pull request merged**
