### PR TITLE
update to DSU_18.08.00

### PR DESCRIPTION
**Pull request by juliantaylor**
Tested to produce the same metrics on PowerEdge R630 and PowerEdge R640

### CODE REVIEW

**Comment by juliantaylor** [comment]
it would be great if you could push a new version of the docker image to the hub.

**Comment by galexrt** [comment]
Thanks for the PR!
Sure, will do in a few minutes. I'll let you know when the tag has been created and built.

**Comment by galexrt** [comment]
(Image) Tag `v1.3.5` contains your PR. Tag has been pushed and images built.

**Comment by juliantaylor** [comment]
thanks

**Pull request merged**
