### PR TITLE
Addition of Pdisk Hardware Encryption Status

### PR DESCRIPTION
**Pull request by adidiborg**
Hey @galexrt 

Would like to add a metric for checking Hardware Encryption for Pdisks. For Pdisk which are hardware encryption capable, It will show if show if encryption is enabled or not (0 or 1).

### CODE REVIEW

**Comment by galexrt** [comment]
Thanks for the PR!

Seems like you might need to run `go fmt` on the changed code files to get the CI passing: https://github.com/galexrt/dellhw_exporter/runs/7565202837?check_suite_focus=true

Overall the code change looks good, could you please add the `storage_pdisk_storage_encryption` metric to the documentation and examples in the docs?

**Comment by adidiborg** [comment]
Sure will make the changes. Thanks!

**Comment by galexrt** [comment]
@adidiborg Just a thought I had just now, I'm not sure if `storage_pdisk_storage_encryption` is a good name for the Prometheus metrics naming, how about changing it to `storage_pdisk_storage_encrypted`?
That it is easier to distinguish that a pdisk is encrypt 1 (enabled) or 0 (disabled).

**Comment by adidiborg** [comment]
Yes that's a good idea.
Even on my local computer 'make test' seems to be failing after doing 'go fmt'. I'm checking what is wrong.

**Comment by adidiborg** [comment]
oh wait I got it

**Comment by adidiborg** [comment]
Actually I had added test cases for storage encryption, But in yours capability is "No".

**Comment by adidiborg** [comment]
Oh forgot to add in documentation.

**Comment by galexrt** [comment]
@adidiborg It is important to have a test case for this new metrics.

You can create a copy of the test case with `omreport` command output that contains the field(s) for pdisk encryption to be picked up and the correct results.

Let me know if you need help with that, I can gladly add that test case to your branch so we can get this new metric added.

**Comment by adidiborg** [comment]
Okay will get output and add this tomorrow. It's quite late here 🥱

**Comment by galexrt** [comment]
@adidiborg Hi, any update on this PR? I can take over if you don't have the time to work on this anymore.

**Pull request merged**
